FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    build-essential \
    pkg-config

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
